name: Bug report
description: Create a report to help us improve
title: '[Bug]: '

body:
  - type: markdown
    attributes:
      value: |
        重要：請依照該模板來提交 
        Please follow the template to create a new issue
  - type: input
    id: butterfly-ver
    attributes:
      label: 使用的 Butterfly 版本？ | What version of Butterfly are you use?
      description: 檢視主題的 package.json | Check the theme's package.json
    validations:
      required: true

  - type: dropdown
    id: modify
    attributes:
      label: 是否修改过主题文件？ || Has the theme files been modified?
      options:
        - 是 (Yes)
        - 不是 (No)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 使用的瀏覽器？ || What browse are you using?
      options:
        - Chrome
        - Edge
        - Safari
        - Opera
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 使用的系統？ || What operating system are you using?
      options:
        - Windows
        - macOS 
        - Linux
        - Android
        - iOS
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 問題描述 | Describe the bug
      description: 請描述你的問題現象 | A clear and concise description of what the bug is.
      placeholder: 請儘量提供截圖來定位問題 | If applicable, add screenshots to help explain your problem
      value:
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: 出現問題網站 | Website
      description: 請提供下可復現網站地址 | Please supply a website url which can reproduce problem.
      placeholder:
    validations:
      required: true
